http://localhost:3000/

### Get all blocks
http://localhost:3000/blocks

### Add a block
POST http://localhost:3000/blocks

{
    "message": "Data for my block"
}

### Get block By ID
http://localhost:3000/blocks/265a10abd86eebf123361b4f9c3eee9e2cc4bbd0f2b3fe777e001aa8679ad6cf
